# Generated by Django 5.2 on 2025-08-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotherChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mother_id", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=100)),
                ("child_id", models.CharField(max_length=50)),
                ("child_name", models.CharField(max_length=100)),
            ],
        ),
    ]
