# Generated by Django 5.2 on 2025-08-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_role_shiftschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="motherchild",
            name="bed_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
